# Generated by Django 5.0.1 on 2024-02-20 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('S', 'Shirt'), ('TS', 'T-Shirt'), ('JP', 'Jeans Pant'), ('P', 'Normal Pant'), ('CT', 'Coat Tie'), ('LTS', 'Ladies T-Shirt'), ('SR', 'Sharee'), ('TP', 'Three pieces'), ('BR', 'Borkah'), ('SR', 'Sharee'), ('C', 'Cosmetics'), ('SR', 'Sharee'), ('BT', 'Baby Toys'), ('BF', 'Baby Fashion'), ('BM', 'Baby Food')], max_length=200)),
                ('product_image', models.ImageField(upload_to='product_img')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('country', models.CharField(choices=[('Bangladesh', 'Bangladesh'), ('China', 'China'), ('India', 'India'), ('Germany', 'Germany'), ('United States', 'United States'), ('Canada', 'Canada'), ('Japan', 'Japan'), ('Russia', 'Russia'), ('Singapore', 'Singapore'), ('UK', 'UK'), ('UAE', 'UAE'), ('Qatar', 'Qatar')], max_length=200)),
                ('division', models.CharField(choices=[('', 'Choice Your Division'), ('Barishal', 'Barishal'), ('Chattogram', 'Chattogram'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Sylhet', 'Sylhet'), ('Beijing', 'Beijing'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Berlin', 'Berlin'), ('New York', 'New York'), ('San Francisco', 'San Francisco'), ('Washington DC', 'Washington DC'), ('Toronto', 'Toronto'), ('Ottawa', 'Ottawa'), ('Victoria', 'Victoria'), ('Tokyo', 'Tokyo'), ('Moscow', 'Moscow'), ('Singapore', 'Singapore'), ('London', 'London'), ('Abu Dhabi', 'Abu Dhabi'), ('Doha', 'Doha')], max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('thana', models.CharField(max_length=50)),
                ('vill_or_road', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Placed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('', 'Select Your Order'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.customer_profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
            ],
        ),
    ]
